name: zournia_pc
description: "Zournia HUD"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  http: ^1.6.0
  file_picker: ^8.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/  # <--- This tells Flutter to grab EVERYTHING in the folder